### ISSUE TITLE
Web Layout

### ISSUE THREAD

**Issue by pheresi** [pheresi/SHA-webapp#2]
- [x] Define general layout
- [x] Include dropdown menu for UHS with common 50 years probabilities (2, 5, 10, 20, 30, 40 and 50%)
- [x] Include dropdown menu for HC with periods, after IM is selected
- [x] Use Google Maps API for inverse geocoding
- [x] Use three decimal points in the coordinates
- [x] We will be able to have three and possibly four IMs: Sa, SaAvg, FIV3, GIDR. For now, show all of them, but only keep available FIV3 until we run other IMs
- [x] Eliminate risk category
- [x] Soil class dropdown menu: only make available soil classes corresponding to GMPEs of the selected IM
- [x] Change "Shakemap" for "Hazard Map"

**Comment by mibravoh** [comment]
Sunday Progress on Fire!
