### ISSUE TITLE
Hazard curve file name

### ISSUE THREAD

**Issue by mibravoh** [pheresi/SHA-webapp#9]
P, as of now could you save the files, eg:
 
hazard_curve-rlz-000-FIV3(0.1)_1.csv

without using "( )" in the name as the appache linux server does not like files with parenthesis on the file's name. I have changed them to this so far:

hazard_curve-rlz-000-FIV3-0.1-_1.csv

**Comment by pheresi** [comment]
Will do for the future curves! OQ output is with parenthesis, but we can rename them. Also, I'll eliminate the "_1"

**Comment by pheresi** [comment]
Solved
